# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config ## name of ConfigMap; this will be referred from volume definition in deployment file
  labels:
    app: mysql
data:
  ## default_auth is the name of config. This will be referred from volume mount definition subpath
  default_auth: |
    [mysqld]
    default_authentication_plugin=mysql_native_password