apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.6.1-php7.3
        resources:
          limits:
            memory: "128Mi"
            # cpu: "1000m"
        ports:
        - containerPort: 80
          name: http-port
        env:
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: mysql-db-password
      - name: mysql
        image: mysql:8.0.23
        resources:
          limits:
            memory: "1Gi"
            # cpu: "1000m"
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: mysql-db-password
        volumeMounts:
        - name: mysql-config-volume ## specify volume name
          mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
          subPath: default_auth ## name of config
        - name: mysql-datastore
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-config-volume ## volume name
        configMap:
          name: mysql-config ## name of ConfigMap
      - name: mysql-datastore
        persistentVolumeClaim:
          claimName: mysql-pv-claim
