apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
  - port: 32000
    targetPort: http-port
    nodePort: 32000
    protocol: TCP
  type: NodePort
